"""
class_mapping.py
Maps every dataset folder name → unified snake_case class name.
SKIP = not a medicinal plant, excluded from training.
"""

# ─── Archive dataset mapping ───────────────────────────────────────
# Suffix .H = Healthy, .U = Unhealthy → same class (we identify plant, not health)
ARCHIVE_MAP = {
    "Ashok.H":                    "ashoka",
    "Ashok.U":                    "ashoka",
    "Bamboo.U":                   "bamboo",
    "Barlaria.H":                 "barlaria",
    "Bel.H":                      "bael",
    "Bel.U":                      "bael",
    "Clerodendrum splendens.H":   "clerodendrum",
    "Clerodendrum splendens.U":   "clerodendrum",
    "curry.H":                    "curry_leaf",
    "Curry.U":                    "curry_leaf",
    "CustardApple.H":             "custard_apple",
    "CustardApple.U":             "custard_apple",
    "Guava.H":                    "guava",
    "Guava.U":                    "guava",
    "Harsingar.H":                "harsingar",
    "harshingar.U":               "harsingar",
    "hibiscus.H":                 "hibiscus",
    "Hibiscus.U":                 "hibiscus",
    "Jack fruit.H":               "jackfruit",
    "Jack Fruit.U":               "jackfruit",
    "kachnar.H":                  "kachnar",
    "Kachnar.U":                  "kachnar",
    "Lantana.H":                  "lantana",      # ⚠️ Toxic weed
    "Lantana.U":                  "lantana",
    "leafs":                      "SKIP",
    "Lemon.H":                    "lemon",
    "Lemon.U":                    "lemon",
    "Makoy,U":                    "makoy",         # ⚠️ Toxic in large doses
    "Makoy.H":                    "makoy",
    "Marigold.H":                 "marigold",
    "Mint.H":                     "mint",
    "Nasturtium.H":               "nasturtium",
    "Nasturtium.U":               "nasturtium",
    "Papaya.H":                   "papaya",
    "Rose.H":                     "rose",
    "Rose.U":                     "rose",
    "Rose1.H":                    "rose",
    "Rose1.U":                    "rose",
    "Scarlet Sage.H":             "scarlet_sage",
    "Scarlet Sage.U":             "scarlet_sage",
    "Tulsi.H":                    "tulsi",
    "Tulsi.U":                    "tulsi",
}

# ─── Medicinal Leaf dataset mapping ────────────────────────────────
LEAF_DATASET_MAP = {
    "Aloevera":                   "aloe_vera",
    "Amla":                       "amla",
    "Amruthaballi":               "amruthaballi",
    "Arali":                      "arali",          # ⚠️ Nerium oleander — toxic
    "Ashoka":                     "ashoka",
    "ashoka":                     "ashoka",
    "Astma_weed":                 "asthma_weed",
    "Badipala":                   "badipala",
    "Balloon_Vine":               "balloon_vine",
    "Bamboo":                     "bamboo",
    "Beans":                      "SKIP",
    "Betel":                      "betel",
    "Bhrami":                     "brahmi",
    "Bringaraja":                 "bringaraja",
    "camphor":                    "camphor",
    "Caricature":                 "caricature",
    "Castor":                     "castor",
    "Catharanthus":               "catharanthus",
    "Chakte":                     "chakte",
    "Chilly":                     "SKIP",
    "Citron lime (herelikai)":    "citron_lime",
    "Coffee":                     "SKIP",
    "Common rue(naagdalli)":      "common_rue",
    "Coriender":                  "coriander",
    "Curry":                      "curry_leaf",
    "Doddpathre":                 "doddpathre",
    "Drumstick":                  "moringa",
    "Ekka":                       "ekka",
    "Eucalyptus":                 "eucalyptus",
    "Ganigale":                   "ganigale",
    "Ganike":                     "ganike",
    "Gasagase":                   "gasagase",
    "Ginger":                     "ginger",
    "Globe Amarnath":             "globe_amaranth",
    "Guava":                      "guava",
    "Henna":                      "henna",
    "Hibiscus":                   "hibiscus",
    "Honge":                      "honge",
    "Insulin":                    "insulin_plant",
    "Jackfruit":                  "jackfruit",
    "Jasmine":                    "jasmine",
    "kamakasturi":                "kamakasturi",
    "Kambajala":                  "kambajala",
    "Kasambruga":                 "kasambruga",
    "kepala":                     "kepala",
    "Kohlrabi":                   "SKIP",
    "Lantana":                    "lantana",         # ⚠️ Toxic
    "Lemon":                      "lemon",
    "Lemongrass":                 "lemongrass",
    "Malabar_Nut":                "malabar_nut",
    "Malabar_Spinach":            "SKIP",
    "Mango":                      "mango",
    "Marigold":                   "marigold",
    "Mint":                       "mint",
    "Neem":                       "neem",
    "Nelavembu":                  "nelavembu",
    "Nerale":                     "nerale",
    "Nooni":                      "noni",
    "Onion":                      "SKIP",
    "Padri":                      "padri",
    "Palak(Spinach)":             "SKIP",
    "Papaya":                     "papaya",
    "Parijatha":                  "harsingar",       # Same plant as Harsingar
    "Pea":                        "SKIP",
    "Pepper":                     "pepper",
    "Pomoegranate":               "pomegranate",
    "Pumpkin":                    "SKIP",
    "Raddish":                    "SKIP",
    "Rose":                       "rose",
    "Sampige":                    "sampige",
    "Sapota":                     "sapota",
    "Seethaashoka":               "ashoka",
    "Seethapala":                 "custard_apple",
    "Spinach1":                   "SKIP",
    "Tamarind":                   "tamarind",
    "Taro":                       "SKIP",
    "Tecoma":                     "tecoma",
    "Thumbe":                     "thumbe",
    "Tomato":                     "SKIP",
    "Tulsi":                      "tulsi",
    "Turmeric":                   "turmeric",
}

# ─── Medicinal Plant dataset mapping ───────────────────────────────
PLANT_DATASET_MAP = {
    "Aloevera":       "aloe_vera",
    "Amla":           "amla",
    "Amruta_Balli":   "amruthaballi",
    "Arali":          "arali",
    "Ashoka":         "ashoka",
    "Ashwagandha":    "ashwagandha",    # ⭐ Only in this dataset!
    "Avacado":        "SKIP",
    "Bamboo":         "bamboo",
    "Basale":         "SKIP",
    "Betel":          "betel",
    "Betel_Nut":      "betel_nut",
    "Brahmi":         "brahmi",
    "Castor":         "castor",
    "Curry_Leaf":     "curry_leaf",
    "Doddapatre":     "doddpathre",
    "Ekka":           "ekka",
    "Ganike":         "ganike",
    "Gauva":          "guava",
    "Geranium":       "geranium",
    "Henna":          "henna",
    "Hibiscus":       "hibiscus",
    "Honge":          "honge",
    "Insulin":        "insulin_plant",
    "Jasmine":        "jasmine",
    "Lemon":          "lemon",
    "Lemon_grass":    "lemongrass",
    "Mango":          "mango",
    "Mint":           "mint",
    "Nagadali":       "common_rue",
    "Neem":           "neem",
    "Nithyapushpa":   "catharanthus",
    "Nooni":          "noni",
    "Pappaya":        "papaya",
    "Pepper":         "pepper",
    "Pomegranate":    "pomegranate",
    "Raktachandini":  "raktachandini",
    "Rose":           "rose",
    "Sapota":         "sapota",
    "Tulasi":         "tulsi",
    "Wood_sorel":     "wood_sorel",
}

# ─── Human-readable display names (snake_case → pretty name) ───────
DISPLAY_NAMES = {
    "aloe_vera":       "Aloe Vera",
    "amla":            "Amla (Indian Gooseberry)",
    "amruthaballi":    "Amruthaballi (Giloy)",
    "arali":           "Arali (Nerium) ⚠️",
    "ashoka":          "Ashoka Tree",
    "ashwagandha":     "Ashwagandha",
    "asthma_weed":     "Asthma Weed",
    "bael":            "Bael (Bel)",
    "badipala":        "Badipala",
    "balloon_vine":    "Balloon Vine",
    "bamboo":          "Bamboo",
    "barlaria":        "Barleria",
    "betel":           "Betel Leaf (Paan)",
    "betel_nut":       "Betel Nut (Supari)",
    "brahmi":          "Brahmi",
    "bringaraja":      "Bhringraj",
    "camphor":         "Camphor (Kapur)",
    "caricature":      "Caricature Plant",
    "castor":          "Castor (Arandi)",
    "catharanthus":    "Catharanthus (Sadabahar)",
    "chakte":          "Chakte",
    "citron_lime":     "Citron Lime",
    "clerodendrum":    "Clerodendrum",
    "common_rue":      "Common Rue (Naagdalli)",
    "coriander":       "Coriander (Dhaniya)",
    "curry_leaf":      "Curry Leaf (Kadi Patta)",
    "custard_apple":   "Custard Apple (Sitaphal)",
    "doddpathre":      "Doddpathre (Indian Borage)",
    "ekka":            "Ekka (Crown Flower) ⚠️",
    "eucalyptus":      "Eucalyptus (Nilgiri)",
    "ganigale":        "Ganigale",
    "ganike":          "Ganike",
    "gasagase":        "Gasagase (Poppy Seeds)",
    "geranium":        "Geranium",
    "ginger":          "Ginger (Adrak)",
    "globe_amaranth":  "Globe Amaranth",
    "guava":           "Guava (Amrood)",
    "harsingar":       "Harsingar (Parijat)",
    "henna":           "Henna (Mehendi)",
    "hibiscus":        "Hibiscus (Gudhal)",
    "honge":           "Honge (Pongamia)",
    "insulin_plant":   "Insulin Plant",
    "jackfruit":       "Jackfruit (Kathal)",
    "jasmine":         "Jasmine (Chameli)",
    "kachnar":         "Kachnar (Mountain Ebony)",
    "kamakasturi":     "Kamakasturi",
    "kambajala":       "Kambajala",
    "kasambruga":      "Kasambruga",
    "kepala":          "Kepala",
    "lantana":         "Lantana ⚠️ (Toxic)",
    "lemon":           "Lemon (Nimbu)",
    "lemongrass":      "Lemongrass",
    "malabar_nut":     "Malabar Nut (Adulsa)",
    "makoy":           "Makoy (Black Nightshade) ⚠️",
    "mango":           "Mango (Aam)",
    "marigold":        "Marigold (Genda)",
    "mint":            "Mint (Pudina)",
    "moringa":         "Drumstick (Moringa)",
    "nasturtium":      "Nasturtium",
    "neem":            "Neem",
    "nelavembu":       "Nelavembu (Kalmegh)",
    "nerale":          "Indian Blackberry (Jamun)",
    "noni":            "Noni (Nooni)",
    "padri":           "Padri",
    "papaya":          "Papaya (Papita)",
    "pepper":          "Black Pepper (Kali Mirch)",
    "pomegranate":     "Pomegranate (Anar)",
    "raktachandini":   "Raktachandini",
    "rose":            "Rose (Gulab)",
    "sampige":         "Champak (Sampige)",
    "sapota":          "Sapota (Chikoo)",
    "scarlet_sage":    "Scarlet Sage (Salvia)",
    "tamarind":        "Tamarind (Imli)",
    "tecoma":          "Tecoma",
    "thumbe":          "Thumbe",
    "tulsi":           "Tulsi (Holy Basil)",
    "turmeric":        "Turmeric (Haldi)",
    "wood_sorel":      "Wood Sorrel (Ambari)",
}

# ─── Toxic / Needs-Caution plant flags ─────────────────────────────
TOXIC_PLANTS = {"lantana", "arali", "makoy", "ekka"}
CAUTION_PLANTS = {"castor", "catharanthus", "common_rue"}

# ─── AYUSH recognized plants ───────────────────────────────────────
AYUSH_PLANTS = {
    "tulsi", "ashwagandha", "turmeric", "neem", "ginger", "amla",
    "brahmi", "bael", "harsingar", "moringa", "aloe_vera", "mint",
    "guava", "lemon", "hibiscus", "curry_leaf", "pepper", "coriander",
    "lemongrass", "jasmine", "pomegranate", "papaya", "amruthaballi",
    "nelavembu", "bringaraja", "doddpathre", "malabar_nut", "camphor",
    "tamarind", "nerale", "henna", "marigold", "castor",
}
